[package]
name = "browser"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
x11rb = "0.13"
winit = "0.29"
softbuffer = "0.4"
raw-window-handle = "0.6"
resvg = "0.47.0"
reqwest = { version = "0.13.2", features = ["json", "cookies", "gzip"]}
tokio = { version = "1", features = ["full"] }
bytes = "1.11.1"
deno_core = "0.398.0"
url = "2.5.8"
deno_webidl = "0.245.0"
deno_web = "0.276.0"
percent-encoding = "2.3.2"
ab_glyph = "0.2.32"
deno_fetch = "=0.269.0"
deno_net = "=0.237.0"
deno_permissions = "=0.104.0"
rustls = { version = "=0.23.28", default-features = false, features = ["logging", "std", "tls12", "aws_lc_rs"] }
sys_traits = { version = "=0.1.27", features = ["libc", "real"] }
deno_crypto = "=0.259.0"
image = "0.25.10"
fixedbitset = "0.5.7"
deno_error = "=0.7.1"
